### PR TITLE
reduce bitwise instructions

### PR DESCRIPTION
**Pull request by maxbachmann**
I did run into https://tech.popdata.org/speeding-up-Jaro-Winkler-with-rust-and-bitwise-operations/ today and since I have a similar implementation (here: https://github.com/maxbachmann/rapidfuzz-cpp/blob/main/rapidfuzz/distance/Jaro_impl.hpp) I looked into the way your implementation works.

This PR reduces the bitwise instructions used in the inner loop. Be aware, that I did not test this and do not know a ton about rust, so take this with a grain of salt.
Looking at godbolt this seems to help reduce the used instruction quite significantly:
https://rust.godbolt.org/z/dv79vfjfx
to
https://rust.godbolt.org/z/x4KdvYT36

### CODE REVIEW

**Comment by maxbachmann** [comment]
@jakew-umn is there any interest in this? Otherwise I will close the PR.

**Comment by jakew-umn** [comment]
Hi Max, sorry for not getting back to you sooner. I tested out your change this morning and while it did produce accurate results, the run-times were about 2 times slower than on the main branch:

```
➜  pseudo_jaro_winkler (max) cargo run -r input/file_a.txt input/file_b.txt output/
    Finished release [optimized] target(s) in 0.06s
     Running `target/release/pseudo_jaro_winkler input/file_a.txt input/file_b.txt output/`
34687 ms
```


```
➜  pseudo_jaro_winkler (main) cargo run -r input/file_a.txt input/file_b.txt output/
   Compiling pseudo_jaro_winkler v0.1.0 (/Users/jwellington/projects/pseudo_jaro_winkler)
    Finished release [optimized] target(s) in 1.16s
     Running `target/release/pseudo_jaro_winkler input/file_a.txt input/file_b.txt output/`
18291 ms
```

I'm going to close this PR for now, but if you want to do more investigation into the runtime difference we can reopen it.

**Comment by franfabrizio** [comment]
Closing per Jake's note above.

**Comment by maxbachmann** [comment]
At first the benchmark didn't run on my machine since it attempts to open an obscene amount of file handles in parallel (more than 1024). I increased my users file handle limit to run the benchmark.

Looking into it a bit more I noticed that overall this benchmark is insanely bottle necked by the file IO. On my machine it takes around 280 ms without the file writes, but more than 6000 ms with the file writes. In addition it's significantly slower when the files don't exist yet. I assume that's the 2x performance difference you are seeing.

So I created a modified version which does the following:
1) disables all the file io and just stores results in a vector which is passed to a black box so it's not optimized out
2) extend the benchmark to the other libraries that are wrapped for testing purposes
3) add wrapping for https://github.com/rapidfuzz/rapidfuzz-rs/tree/main which provides a bitparallel jaro winkler implementation as well. As a difference to pseudo_jaro_winkler it's not just an approximation, but the actual similarity

Then I get the following results:
```
pseudo_jaro_winkler     time:   [36.577 ms 36.759 ms 37.050 ms]                              
                        change: [-2.4226% -1.1805% +0.1579%] (p = 0.11 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe

strsim_jaro_winkler     time:   [12.535 ms 12.658 ms 12.799 ms]                               
                        change: [+0.8188% +2.1163% +3.5482%] (p = 0.01 < 0.05)
                        Change within noise threshold.

rapidfuzz_jaro_winkler  time:   [6.1606 ms 6.2320 ms 6.3163 ms]                                  
                        change: [-0.4910% +3.4319% +7.3693%] (p = 0.12 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild

eddie_jaro_winkler      time:   [11.541 ms 11.692 ms 11.813 ms]                              
                        change: [-4.3862% -1.9119% +0.3474%] (p = 0.16 > 0.05)
                        No change in performance detected.
```


I then modified the benchmark to use `input/file_a.txt` and `input/file_b.txt` instead and suddenly `pseudo_jaro_winkler` was way ahead of everyone else. This mostly comes down to the dataset being incredibly huge while ~98% of all comparisions are duplicates.
None of the other libraries do this and so it's obviously way faster. For all others this would be a preprocessing step the user would do if he knows his dataset might contain lots of duplicates. So I decided to dedup the lists beforehand since that's expected by users of the other libraries if their dataset contains lots of duplicates.


Even when deduplicating ahead of time this is still faster than my own bitparallel implementation in `rapidfuzz`:
```
pseudo_jaro_winkler     time:   [189.71 ms 190.42 ms 191.36 ms]                              
                        change: [-0.0178% +0.7303% +1.4053%] (p = 0.08 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high severe

Benchmarking rapidfuzz_jaro_winkler: Warming up for 1.0000 s
Warning: Unable to complete 10 samples in 1.0s. You may wish to increase target time to 5.7s.
rapidfuzz_jaro_winkler  time:   [551.92 ms 557.12 ms 563.46 ms]                                 
                        change: [+0.1912% +1.3991% +2.8379%] (p = 0.06 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
  1 (10.00%) high mild
```
I will probably look into this performance difference a bit more. Most of it is probably because `pseudo_jaro_winkler` only approximates the transposition count. However maybe there is still something else going on.


In this case my bit operation change reduces the runtime on my machine by around 10-12%. 
```
pseudo_jaro_winkler     time:   [188.77 ms 189.47 ms 190.37 ms]                              
                        change: [-12.425% -11.887% -11.395%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 1 outliers among 10 measurements (10.00%)
```
vs
```
pseudo_jaro_winkler     time:   [214.29 ms 215.03 ms 216.04 ms]                              
                        change: [-0.4928% +0.1500% +0.7933%] (p = 0.69 > 0.05)
                        No change in performance detected.
Found 1 outliers among 10 measurements (10.00%)
```

so the change does appear to help. Obviously the runtime difference is relatively small when everything is dominated by the file io.

**Comment by maxbachmann** [comment]
https://github.com/maxbachmann/pseudo_jaro_winkler/tree/patch-1 contains my patched version. Obviously everything except for the bit operation changes are not meant for direct inclusion.

**Comment by jakew-umn** [comment]
Unfortunately, I don't have much time to continue to dig into this. I think we're going to have to keep it closed for the time being as it is a performance improvement and not a more urgent bug fix.

**Comment by maxbachmann** [comment]
That's completely fine with me. I just noticed the difference when comparing the two implementations and so figured I might as well create a PR with it.

**Pull request closed without merging**
